### ISSUE TITLE
Missing products

### ISSUE THREAD

**Issue by SirPando** [SirPando/web_document_T02#10]
Is there any chance the rest of our Products (description in the ``data-file.xml`` on ``main``-branch) will apear on the website please?
@Bahramrj @flxlet

**Comment by Bahramrj** [comment]
Hello  @SirPando 
Yes, I can add more products if you want but we have already reached 10 web pages for the Assignment.
the efficient way to add all products can be done by scripts, which we are not allowed. without java-script and... I have to duplicate an HTML page for all products (around 33 HTML pages).
But if you want I can add some more of them? :wink:
Thank you

**Comment by SirPando** [comment]
Everything is okay so. Thx
