### ISSUE TITLE
Github pages

### ISSUE THREAD

**Issue by Bahramrj** [SirPando/web_document_T02#5]
Hello, can you please change GitHub pages to **Develop** branch (`/docs` as root)? To see the website in action.

**Comment by BMD91** [comment]
We got some problems with github. We will figure it out and deploy it as soon as possible

**Comment by BMD91** [comment]
Bahram, try to place "docs" outside that assignment_2b, and then we can deploy website

**Comment by BMD91** [comment]
... or Felix can do it   xD

**Comment by Bahramrj** [comment]
hi, I tried to move the docs folder but I think messed up my local repo :D

**Comment by BMD91** [comment]
I got the same ordered folders as your, and I have just done it from my local.
First, move "docs" and all its contents out of "assignment-2b". Now "assignment-2b" has nothing, and you can delete it.
Then commit a new one and push them to branch "Develop".
It will be well organized.
The importance is, all original files still in your computer, so don't worry  :D

**Comment by Bahramrj** [comment]
thanks 🙏, It worked. The docs folder has now been relocated outside of the assignment_2b folder.

**Comment by Bahramrj** [comment]
Hi, the website is still not reachable on Github pages.

**Comment by Bahramrj** [comment]
@BMD91 @SirPando Thanks it's working now.

**Comment by SirPando** [comment]
sry, it was a problem in the settinge. I'm glad i could help
