### ISSUE TITLE
I still don't see my pushes.

### ISSUE THREAD

**Issue by flxlet** [SirPando/web_document_T02#9]

**Comment by BMD91** [comment]
you can use GitHub Desktop, it will show you all problems and conflicts 🗡️

**Comment by flxlet** [comment]
i just use the  integrated vsc source control and git bash

**Comment by SirPando** [comment]
i dont know how but it seems you did somehow your own project from ours. 
![grafik](https://user-images.githubusercontent.com/55176629/149762075-a7373166-ebb1-449f-a286-c2b07cc2f084.png)

**Comment by SirPando** [comment]
as senn on the pic you are not working on our ``develop-branch``

**Comment by BMD91** [comment]
delete conflict in that data, the first 2 descriptions of in house tree

**Comment by SirPando** [comment]
now it seems to work 
![grafik](https://user-images.githubusercontent.com/55176629/149764044-c5a8a5b0-f44a-4e60-87f2-dc41e9e3eb53.png)
can you delete your wrong branch pls?

**Comment by SirPando** [comment]
and the structure need to stay as ``develop/docs`` and not ``develop/Assignment_2b/docs`` because otherwise gh-pages doesnt find the files

**Comment by flxlet** [comment]
Yes, i changed it.

**Comment by SirPando** [comment]
so i think this issue is now done.
